repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10.14

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        args:
          - --ignore=E501,F541,F841,B006,E402,E266,F401,F811  # Ignore specific flake8 errors
          - --max-line-length=10000000
