version: '3.8'

services:
  orison-frontend:
    image: orison-frontend
    container_name: orison-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"

  orison-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    tty: true
    stdin_open: true
    image: orison
    container_name: orison
    volumes:
      - ../:/app
    ports:
      - "8888:8888"
      - "5004:5004"
      - "5005:5005"