# Use the official Node.js image from the Docker Hub
FROM node:22

# Set the working directory
WORKDIR /app/frontend/orison-frontend

# Copy the rest of your application code
COPY ./frontend/orison-ai-frontend .
RUN npm install
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]