# Use the official Node.js image from the Docker Hub
FROM node:22

# Set the working directory
WORKDIR /app/frontend/orison-frontend

# Copy the rest of your application code
COPY ./frontend/orison-ai-frontend .
COPY ./frontend/orison-ai-frontend/package*.json ./
RUN npm install

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]