openapi: 3.0.3
info:
  title: OrisonAI API
  description: |-
    The OrisonAI API assists visa attorneys in helping applicants apply for visas based on their experience.
    It also helps attorneys screen applicants, enabling them to focus on the most promising candidates.
  version: 0.1.0
servers:
  - url: https://0ce3b64f-175d-4856-abcf-073461b968bf.mock.pstmn.io
tags:
  - name: scholar
    description: Operations related to Google Scholar processing
  - name: file
    description: Operations related to file vectorization
  - name: summarization
    description: Operations related to summarization
paths:
  /process-scholar-link:
    post:
      tags:
        - scholar
      summary: Process a Google Scholar link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScholarLinkRequest'
      responses:
        '202':
          description: Processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithRequestId'
  /vectorize-files:
    post:
      tags:
        - file
      summary: Start vectorization of uploaded files
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorizeFilesRequest'
      responses:
        '202':
          description: Vectorization started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithRequestId'
  /summarize:
    post:
      tags:
        - summarization
      summary: Start summarization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizationRequest'
      responses:
        '202':
          description: Summarization started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithRequestId'
  /gateway:
    post:
      tags:
        - scholar
        - file
        - summarization
      summary: Redirect request to the correct function
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                or_request_type:
                  type: string
                  enum: [process-scholar-link, vectorize-files, summarize]
                  example: "process-scholar-link"
                or_request_payload:
                  oneOf:
                    - $ref: '#/components/schemas/ScholarLinkRequest'
                    - $ref: '#/components/schemas/VectorizeFilesRequest'
                    - $ref: '#/components/schemas/SummarizationRequest'
      responses:
        '202':
          description: Request received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWithRequestId'
components:
  schemas:
    ScholarLinkRequest:
      type: object
      properties:
        attorneyId:
          $ref: '#/components/schemas/AttorneyId'
        applicantId:
          $ref: '#/components/schemas/ApplicantId'
        scholarLink:
          type: string
          example: "https://scholar.google.com/citations?user=..."
      required:
        - attorneyId
        - applicantId
    VectorizeFilesRequest:
      type: object
      properties:
        attorneyId:
          $ref: '#/components/schemas/AttorneyId'
        applicantId:
          $ref: '#/components/schemas/ApplicantId'
        fileIds:
          type: array
          items:
            type: string
            example: "file-12345"
      required:
        - attorneyId
        - applicantId
    SummarizationRequest:
      type: object
      properties:
        attorneyId:
          $ref: '#/components/schemas/AttorneyId'
        applicantId:
          $ref: '#/components/schemas/ApplicantId'
      required:
        - attorneyId
        - applicantId
    AttorneyId:
      type: string
      example: "attorney-12345"
    ApplicantId:
      type: string
      example: "applicant-12345"
    RequestId:
      type: string
      example: "request-12345"
    ResponseWithRequestId:
      type: object
      properties:
        data:
          type: object
          properties:
            requestId:
              $ref: '#/components/schemas/RequestId'
