# This is a basic workflow to help you get started with Actions
name: orison_staging_deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ staging ]

  pull_request:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v2'
        with:
          name: 'gateway_function_staging'
          source_dir: './src/orison_ai/gateway_function'
          runtime: 'python310'
          memory: '512M'
          min_instance_count: 0
          max_instance_count: 5
          service_timeout: 540
          environment: 'GEN_2'
          region: "us-central1"
          build_environment_variables: |-
            FUNCTION_MODE=gateway_function_staging
          build_service_account: orison-ai-visa-apply@appspot.gserviceaccount.com