# This is a basic workflow to help you get started with Actions
name: orison_staging_deploy

# Controls when the action will run. 
on:
  push:
    branches: [ staging, devel ]

  pull_request:
    branches: [ staging ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_staging:
    if: github.ref == 'refs/heads/staging'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        with:
          name: 'gateway_function_staging'
          source_dir: './src/orison_ai/gateway_function'
          runtime: 'python310'
          memory: '1024M'
          min_instance_count: 0
          max_instance_count: 5
          service_timeout: 540
          environment: 'GEN_1'
          region: "us-central1"
          build_environment_variables: |-
            FUNCTION_MODE=gateway_function_staging
          service_account: orison-ai-visa-apply@appspot.gserviceaccount.com
          # max_instance_request_concurrency: 5 # Explore this later

  build_devel:
    if: github.ref == 'refs/heads/devel'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        with:
          name: 'gateway_function'
          source_dir: './src/orison_ai/gateway_function'
          runtime: 'python310'
          memory: '1024M'
          min_instance_count: 0
          max_instance_count: 5
          service_timeout: 540
          environment: 'GEN_1'
          region: "us-central1"
          build_environment_variables: |-
            FUNCTION_MODE=gateway_function
          service_account: orison-ai-visa-apply@appspot.gserviceaccount.com
          # max_instance_request_concurrency: 5 # Explore this later